### ISSUE TITLE
Asset from Neo - field missing in sidebar

### ISSUE THREAD

**Issue by jeffreyschmitz87** [MindseekerMedia/craft-related-elements#1]
First of all, great plugin!

I added 2 images to an entry. 1 image is added to an Asset - field and 1 image is added to an Asset - field within a Neo - field. The  image inside the Neo - field is not shown in the sidebar (see screenshot).

![Screenshot 2024-09-20 at 11 34 22](https://github.com/user-attachments/assets/b3406051-d2da-4dce-b481-261b82b77f18)

Is it possible to also add the related image in the sidebar?

**Comment by MindseekerMedia** [comment]
@jeffreyschmitz87 Apologies for the late response, and thank you! 

That's a valid point, and the same applies to elements linked in Matrix fields.
It would be a great enhancement, I'll look into it.

**Comment by MindseekerMedia** [comment]
@jeffreyschmitz87 added in 1.1.0
